# Generated by Django 4.1.7 on 2023-07-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('categoria', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('unisex', 'Unisex')], max_length=10)),
                ('descricao', models.TextField(max_length=1000)),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
            ],
        ),
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('descricacao', models.TextField(max_length=1000)),
                ('preco', models.FloatField()),
                ('foto1', models.ImageField(upload_to='fotos_festa')),
                ('foto2', models.ImageField(upload_to='fotos_festa')),
                ('foto3', models.ImageField(upload_to='fotos_festa')),
                ('foto4', models.ImageField(null=True, upload_to='fotos_festa')),
                ('foto5', models.ImageField(null=True, upload_to='fotos_festa')),
                ('foto6', models.ImageField(null=True, upload_to='fotos_festa')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festas', to='PegeMonte.tema')),
            ],
        ),
    ]
